apiVersion: 1

datasources:
  - name: InfluxDB-AgroSat
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: fiap
      defaultBucket: agrosat
      tlsSkipVerify: true
    secureJsonData:
      token: agrosat-super-secret-token-2026
    isDefault: true
    editable: true
