# Mosquitto MQTT Broker - AgroSat Monitor
# FIAP GS 2026.1

listener 1883
protocol mqtt

listener 9001
protocol websockets

# Permitir conexões sem autenticação (dev/wokwi)
allow_anonymous true

# Para produção, descomentar e usar autenticação:
# allow_anonymous false
# password_file /mosquitto/config/passwd

persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_type all

# Limites
max_connections 100
max_queued_messages 1000
message_size_limit 10240
